USE mysql;
DROP DATABASE IF EXISTS companyDB;
DROP TABLE IF EXISTS company;
CREATE DATABASE IF NOT EXISTS companyDB;
USE companyDB;

CREATE TABLE IF NOT EXISTS company
(
    id       INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(40)  NOT NULL,
    location VARCHAR(100) NOT NULL,
    INDEX (name)
) engine = InnoDB;

SELECT *
FROM company;